apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
  nodeSelector:
    # Esta etiqueta esta dentro de la Label q aparece cuando haces kubectl get nodes --show-labels
    # Cambiar el = por :
    kubernetes.io/hostname: minikube-m02
    