version: '3.9'

services:
  app:
    restart: always
    environment:
      DEBUG: "True"
    build: 
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "5000:5000"
    volumes:
      # Aqui montamos como volumen src dentro del container, para poder ver cambios en tiempo real.
      - ./src/:/app/src/
      - logvolume01:/var/logvolume
  # Agregamos una base de datos
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # volumes:
    #   - db:/var/lib/mysql
  # Gestor de bases de datos web
  adminer:
    restart: always
    image: adminer
    ports:
      - '8080:8080'
  
# Cramos un volumen que guarde los logs que pudieran caer en /var/logvolume
volumes:
  logvolume01: {}
  # db: {}
