version: '3.9'
services:
  project:
    build: 
      # Ubicacion del dockerfile para el projecto.
      context: ./project
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    environment:
      - AWS_ACCESS_KEY=value1
      - AWS_SECRET_ACCESS_KEY=value2
      - AWS_DEFAULT_REGION=VALUE3
    container_name: Proyecto  
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile