# En este codigo se despliega un cluster, mediante codigo
apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig

metadata:
  name: mi-cluster
  region: us-east-1

vpc:
  clusterEndpoints:
    publicAccess: true   
    privateAccess: false

managedNodeGroups:
  - name: group-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true # Activar acceso via ssh