# En este codigo se despliega un cluster, mediante codigo
apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig

metadata:
  name: mi-cluster
  region: us-east-1

managedNodeGroups:
  - name: nodegroup-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true # Activar acceso via ssh