version: "3.9"
services:
  web:
    # Construimos mediante imagen, directamente
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      # Volumen bind mount que monta nuestra carpeta local prueba en esa ruta del container
      - ./prueba/:/usr/share/nginx/html
      # Se monta el volumen en esa direccion donde los logs seran almacenados
      - logvolume01:/var/log
    # Aseguramos que redis y web esten en la misma red
    links:
      - redis

  redis:
    image: redis

# Creamos un volumen para nginx guarde ahi los logs
volumes:
  logvolume01: {}