# Forma de un manifest para definir un pod. Si ejecutamos este codigo con su kubectl apply -f 
# pod.yaml y luego kubectl get all veremos el nuevo objeto tipo pod llamado nginx

apiVersion: v1 # Version de la appi de kubernetes
kind: Pod # Tipo
metadata: # Datos adicionales
  name: nginx
  namespace: miespacio # Agregamos el namespace bajo el cual se creara el pod
  labels: # Agregamos mas metadata, aqui puede ser cualquier etiqueta
    project: pagina_web
    enviroment: testing
spec: # Especifica la configuracion de los containers
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80