apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-volumes
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # El volumen compartido
      volumes:
      - name: compartido
        persistentVolumeClaim:
          claimName: www-compartido
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /datos/
        - name: compartido
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # Creacion de los volume Claim para cada PV de cada Pod
  - metadata:
      name: www
    spec: 
      accessModes: ["ReadWriteOnce"] # Debe ser un array
      storageClassName: "manual"
      resources:
        requests:
          storage: 1Gi

# Con los 3 volumenes creados ya se puede crear este y sus pods vincuados a cada volumen. Si
# eliminas con kubectl delete -f statefulset_volume.yaml no se eliminaran los PVC ni los PV.
# S nos conectamos a los 3 pods y nos colocamos en la direccion /usr/share/nginx/html veremos
# lo mismo pues es volumen compartido. Pero si nos vamos a /datos/, cda pod tendra su
# contenido