apiVersion: v1
kind: Service
metadata: 
  labels:
    service: nginx
  name: all-http
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80 # El puerto donde se expone el container
  selector: 
    # Ponemos la etiqueta correspondiente para que pueda ser manejado por nuestro Pod
    # con label service: nginx
    service: nginx 
  type: NodePort