apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: ebs-sc # Nombre de la storageClass creada
  resources:
    requests:
      storage: 4Gi